CREATE VIEW NUMBER_OF_SIBLINGS AS
SELECT COUNT("Count") AS "Students",
	"Count" AS "Number of Siblings"
FROM
	(SELECT "ID",
			COUNT(*) AS "Count"
		FROM
			(SELECT SIBLING_ID_1 AS "ID"
				FROM BRIDGE_SIBLING
				UNION ALL SELECT SIBLING_ID_2 AS "ID"
				FROM BRIDGE_SIBLING) AS STUDENTS_WITH_SIBLINGS
		GROUP BY "ID") AS COUNTED_SIBLINGS
GROUP BY "Count"
UNION
SELECT COUNT(*) AS "Students",
	0 AS "Number of Siblings"
FROM STUDENT
WHERE NOT EXISTS
		(SELECT SIBLING_ID_1
			FROM BRIDGE_SIBLING
			WHERE SIBLING_ID_1 = STUDENT.DATABASE_ID
				OR SIBLING_ID_2 = STUDENT.DATABASE_ID )
ORDER BY "Number of Siblings"

--Example on how to use it
--SELECT *
--FROM NUMBER_OF_SIBLINGS
