CREATE VIEW overworked_employees AS 
SELECT DISTINCT INSTRUCTORS.DATABASE_ID AS "Employee_ID",
	INSTRUCTORS.FULL_NAME AS "Name",

	(SELECT COUNT(*)
		FROM PRIVATE_LESSON
		WHERE PRIVATE_LESSON.INSTRUCTOR_DB_ID = INSTRUCTORS.DATABASE_ID) AS "Private Lessons",

	(SELECT COUNT(*)
		FROM GROUP_LESSON
		WHERE GROUP_LESSON.INSTRUCTOR_DB_ID = INSTRUCTORS.DATABASE_ID) AS "Group Lessons",

	(SELECT COUNT(*)
		FROM ENSEMBLE
		WHERE ENSEMBLE.INSTRUCTOR_DB_ID = INSTRUCTORS.DATABASE_ID) AS "Ensemble Lessons",
	(
			(SELECT COUNT(*)
				FROM PRIVATE_LESSON
				WHERE PRIVATE_LESSON.INSTRUCTOR_DB_ID = INSTRUCTORS.DATABASE_ID) +
			(SELECT COUNT(*)
				FROM GROUP_LESSON
				WHERE GROUP_LESSON.INSTRUCTOR_DB_ID = INSTRUCTORS.DATABASE_ID) +
			(SELECT COUNT(*)
				FROM ENSEMBLE
				WHERE ENSEMBLE.INSTRUCTOR_DB_ID = INSTRUCTORS.DATABASE_ID)) AS "Total",
	EXTRACT(MONTH FROM date) AS "Month"
FROM INSTRUCTORS
JOIN PRIVATE_LESSON ON INSTRUCTORS.DATABASE_ID = PRIVATE_LESSON.INSTRUCTOR_DB_ID
JOIN GROUP_LESSON ON INSTRUCTORS.DATABASE_ID = GROUP_LESSON.INSTRUCTOR_DB_ID
JOIN ENSEMBLE ON INSTRUCTORS.DATABASE_ID = ENSEMBLE.INSTRUCTOR_DB_ID
JOIN BOOKING_TABLE ON PRIVATE_LESSON.DATABASE_ID = BOOKING_TABLE.PRIVATE_LESSON_DB_ID
OR GROUP_LESSON.DATABASE_ID = BOOKING_TABLE.GROUP_LESSON_DB_ID
OR ENSEMBLE.DATABASE_ID = BOOKING_TABLE.ENSEMBLE_DB_ID
WHERE EXTRACT(MONTH FROM date) = EXTRACT(MONTH FROM CURRENT_DATE)
AND EXTRACT(YEAR FROM date) = EXTRACT(YEAR FROM CURRENT_DATE)
ORDER BY "Total" DESC;

--Example on how to use it
-- SELECT *
-- FROM OVERWORKED_EMPLOYEES
-- WHERE "Total" > 3
