CREATE TABLE STUDENTS_AND_LESSONS
(
	DATABASE_ID SERIAL UNIQUE NOT NULL,
    STUDENT VARCHAR(500),
    STUDENT_ID VARCHAR(100),
    DISCOUNT VARCHAR(100),
    LESSON_ID VARCHAR(100),
    TYPE VARCHAR(100),
    DATE DATE,
    CLASSROOM VARCHAR(100),
    INSTRUCTOR VARCHAR(500),
    EMPLOYEE_ID VARCHAR(100),
    BASE_PRICE INTEGER,
    SIBLING_DISCOUNT_MODIFER REAL
);