CREATE VIEW DENORMALIZED_LESSONS AS
SELECT GROUP_LESSON.DATABASE_ID,
	GROUP_LESSON.LESSON_ID,
	GROUP_LESSON.SKILL_LEVEL,
	GROUP_LESSON.INSTRUMENT,
	NULL AS GENRE,
	GROUP_LESSON.MIN_NUMBER_OF_STUDENTS,
	GROUP_LESSON.MAX_NUMBER_OF_STUDENTS,
	GROUP_LESSON.INSTRUCTOR_DB_ID
FROM GROUP_LESSON
UNION
SELECT ENSEMBLE.DATABASE_ID,
	ENSEMBLE.LESSON_ID,
	ENSEMBLE.SKILL_LEVEL,
	NULL,
	ENSEMBLE.GENRE,
	ENSEMBLE.MIN_NUMBER_OF_STUDENTS,
	ENSEMBLE.MAX_NUMBER_OF_STUDENTS,
	ENSEMBLE.INSTRUCTOR_DB_ID
FROM ENSEMBLE
UNION
SELECT PRIVATE_LESSON.DATABASE_ID,
	PRIVATE_LESSON.LESSON_ID,
	PRIVATE_LESSON.SKILL_LEVEL,
	PRIVATE_LESSON.INSTRUMENT,
	NULL,
	NULL,
	NULL,
	PRIVATE_LESSON.INSTRUCTOR_DB_ID
FROM PRIVATE_LESSON;