SELECT STUDENT.FULL_NAME AS "Student",
	STUDENT_ID,
	LESSON_ID, date, CLASSROOM,
	INSTRUCTORS.FULL_NAME AS "Instructor",
	EMPLOYEE_ID,
	PRIVATE_LESSON_BASE_PRICE,
	SIBLING_DISCOUNT_MODIFIER
FROM PRIVATE_LESSON
INNER JOIN BOOKING_TABLE ON PRIVATE_LESSON_DB_ID = PRIVATE_LESSON.DATABASE_ID
INNER JOIN INSTRUCTORS ON INSTRUCTORS.DATABASE_ID = INSTRUCTOR_DB_ID
INNER JOIN PRICE_TABLE ON BOOKING_TABLE.DATE BETWEEN START_DATE AND END_DATE
INNER JOIN BRIDGE_STUDENT_TO_BOOKING ON BOOKING_DB_ID = BOOKING_TABLE.DATABASE_ID
INNER JOIN STUDENT ON STUDENT_DB_ID = STUDENT.DATABASE_ID